az keyvault secret download --file /path/to/cert.pfx --vault-name VaultName --name CertName --encoding base64 openssl pkcs12 -in cert.pfx -passin pass: -out cert.pem -nodes


on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.GET_APP_SP }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'storagePrefix=labbicep storageSKU=Standard_LRS'
        failOnStdErr: false
